FROM node:22 AS build-stage
WORKDIR /app
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build


FROM nginx:alpine
COPY --from=build-stage /app/dist/task-manager-frontend/browser /usr/share/nginx/html
EXPOSE 80